# Generated by Django 3.0.3 on 2020-02-22 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=200)),
                ('school_city', models.CharField(max_length=50)),
                ('school_state', models.CharField(max_length=50)),
                ('school_zip', models.CharField(max_length=10)),
                ('school_email', models.EmailField(max_length=100)),
                ('school_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
