# Generated by Django 3.0.3 on 2020-02-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0002_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='school_id',
            new_name='school',
        ),
    ]
