# Generated by Django 3.0.3 on 2020-02-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0004_auto_20200222_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='school_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.School'),
        ),
    ]
