# Generated by Django 3.0.3 on 2020-02-22 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0005_auto_20200222_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_middle_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('student_dateofbirth', models.DateTimeField(max_length=50)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_address', models.CharField(max_length=200)),
                ('student_city', models.CharField(max_length=50)),
                ('student_state', models.CharField(max_length=50)),
                ('student_zip', models.CharField(max_length=10)),
                ('student_phone', models.CharField(max_length=50)),
                ('student_school', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.Grade')),
                ('school', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.School')),
            ],
        ),
    ]
