# Generated by Django 3.0.3 on 2020-02-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_school',
        ),
    ]
