# Generated by Django 3.0.3 on 2020-02-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0007_remove_student_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
