# Generated by Django 3.0.3 on 2020-02-22 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0008_auto_20200222_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_first_name', models.CharField(max_length=100)),
                ('mentor_middle_name', models.CharField(blank=True, max_length=100)),
                ('mentor_last_name', models.CharField(max_length=100)),
                ('mentor_email', models.EmailField(max_length=100)),
                ('mentor_address', models.CharField(max_length=200)),
                ('mentor_city', models.CharField(max_length=50)),
                ('mentor_state', models.CharField(max_length=50)),
                ('mentor_zip', models.CharField(max_length=10)),
                ('mentor_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
