# Generated by Django 3.0.3 on 2020-02-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0010_student_group_mentor_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_group_mentor_assignment',
            unique_together={('school', 'grade')},
        ),
    ]
