# Generated by Django 3.0.3 on 2020-02-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0011_auto_20200222_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('grade_num', 'school')},
        ),
    ]
