# Generated by Django 3.0.3 on 2020-02-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0015_auto_20200222_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='grade_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='school_id',
        ),
    ]
