# Generated by Django 3.0.3 on 2020-02-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0016_auto_20200222_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_id',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradess', to='sma.Grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='sma.Grade'),
        ),
    ]
